---
route:
  repeat_interval: 30m
  group_interval: 30m
  receiver: 'rocketchat'

receivers:
  - name: 'rocketchat'
    webhook_configs:
      - send_resolved: false
        url: 'https://EXAMPLE.COM/hooks/............'
